### ISSUE TITLE
Measure quality of overapproximation

### ISSUE THREAD

**Issue by mforets** [JuliaReach/IntervalMatrices.jl#143]
It is useful to have a function that measures the "width" of the overapproximation. A proposal from [1],

>  Let wid M be the real matrix formed of the widths of the
entries of M. We will use the kwid Mk as a quality measure of the enclosure M

can be implemented like so:

```julia
julia> width(A) = opnorm(diam.(A), Inf)
```
I don't know if `width` is a good name though.

[1] https://www.mat.univie.ac.at/~neum/ms/intExp.pdf

**Comment by schillic** [comment]
I agree that `width` is misleading. They call `dim A` (`diam.(A)`) the *width* and `||dim A||` (`opnorm(diam.(A))`) their *quality measure*. Maybe `diam_quality` or just `quality`? I do not completely like that because it is only a relative measure (knowing the quality for a single matrix does not tell you much). Maybe just a name that describes what it does: `diam_norm`.

**Comment by mforets** [comment]
Actually i like `width`, i think that it conveys the idea of the "width" of the given interval matrix.

**Comment by schillic** [comment]
But it is not the width?!? The width is what we call `diam`. I find it very confusing to offer both `diam` and `width` with different meanings.
`width_norm`/`width_inf`/`normalized_width`?

**Comment by mforets** [comment]
Well, `width` has not been taken, so i don't see a problem given that we add documentation explaining what it does.

Otherwise,  i agree to call the function `diam_norm`.

**Comment by schillic** [comment]
I am fine with anything but `width`.
