### ISSUE TITLE
Review exp_overapproximation name

### ISSUE THREAD

**Issue by mforets** [JuliaReach/IntervalMatrices.jl#176]
In the context of IA, all functions may overapproximate, so I suggest to rename what is now `exp_overapproximate` to just `exp`.

**Comment by schillic** [comment]
I think this was meant in contrast to `exp_underapproximation`. I do not remember if that is really an underapproximation of the true result or (my preference) it is just an underapproximation of `exp_overapproximate`. Note that the docstring is not helpful because I think it just has a typo there.

https://github.com/JuliaReach/IntervalMatrices.jl/blob/a892aed8ad1ac12ec99a0c05005b3a7d413d9862/src/exponential.jl#L319-L321

**Comment by lucaferranti** [comment]
what is an underapproximation of an overapproximation? Is it computed by some probablistic algorithm which may leave out a portion x of the true solution set?

**Comment by schillic** [comment]
No, I meant just a subset of the overapproximation.
But I checked again and I think I have to correct myself: here it is really an underapproximation of the exact result.
